(function () {
  const I18N = {
    ru: {
      brand: "Threads AI",
      newChat: "Новый чат",
      settings: "Настройки",
      placeholder: "Спросите ИИ…",
      emptyTitle: "Готов к работе",
      emptySteps: "Спросите: «Что сейчас в ленте?»\n«Найди посты про дизайн»\n«Напиши пост про отпуск»\n«Ответь на комментарии к этому посту»",
      setupTitle: "Нужен API-ключ",
      setupSteps: "Откройте настройки (шестерёнка)\nи вставьте ключ DeepSeek\nили OpenCode Zen — и можно начинать",
      setupBtn: "Настройки",
      errNoTab: "Откройте вкладку Threads (threads.com) — расширение работает только там.",
      errNotConnected: "Расширение не подключено к странице. В Safari: Настройки (⌘,) → Расширения → «Threads AI» → «Разрешить доступ»: выберите «Для всех сайтов», затем обновите вкладку (Cmd+R).",
      cancel: "Отмена",
      publish: "Опубликовать",
      send: "Отправить",
      publishing: "Публикуем…",
      publishLabelPost: "Пост готов к публикации",
      publishLabelReply: "Ответ готов к отправке",
      connNoKey: "нет ключа",
      connNoTab: "нет вкладки",
      connThreads: "Threads",
      sTitle: "Настройки",
      sSub: "Помощник на базе DeepSeek для Threads",
      sConn: "Подключение",
      sApiKey: "API-ключ",
      show: "Показать",
      hide: "Скрыть",
      sBaseUrl: "Base URL",
      sModel: "Модель",
      sCheck: "Проверить подключение",
      sLang: "Язык интерфейса",
      sLangLabel: "Язык",
      sAuto: "Автоматизация",
      sAutoOn: "Автозапуск по расписанию",
      sInterval: "Интервал (минут)",
      sTask: "Задача для ИИ",
      sRunNow: "Запустить сейчас",
      sAutoNote: "Авто-режим читает ленту и составляет отчёт. Публикация и ответы — только с вашего подтверждения.",
      sStyle: "Мой стиль",
      sStyleNote: "AI изучит ваши посты (откроет ваш профиль в Threads) и запомнит, как вы пишете: тон, длину, эмодзи, хэштеги. Затем будет писать посты и комментарии в вашей манере.",
      sStudy: "Изучить мой стиль",
      sClear: "Очистить",
      sChecking: "Проверяю…",
      sCheckOk: "Подключено. Модель {m}.",
      sCheckOkNoModel: "Подключено. Модель «{m}» не в списке, но можно попробовать.",
      sRunning: "Запускаю…",
      sDone: "Готово",
      sRunFail: "Не удалось запустить",
      sNeedTab: "Откройте вкладку Threads (threads.com) — расширение работает только там.",
      sStudying: "Изучаю ваш профиль… это займёт ~30 секунд",
      sStudyDone: "Готово! Стиль сохранён.",
      sStudyFail: "Не удалось изучить стиль",
      sNoPosts: "На профиле не нашлось постов — напишите пару постов и попробуйте снова.",
      sCleared: "Стиль очищен.",
      sLastRun: "Последний запуск {time}{err}",
      sErrSuffix: " (с ошибкой)",
      sHistory: "История чатов",
      sEmptyHistory: "Пока нет сохранённых чатов",
      sDel: "Удалить чат",
      sOpen: "Открыть чат",
      sNewChatTitle: "Чат",
      sRefreshing: " (обновляю вкладку Threads)…",
      sProfile: "Мой профиль",
      sStyleEdit: "Ваш стиль — можно редактировать вручную",
      sStylePh: "Стиль ещё не изучен. Нажмите «Изучить мой стиль» — или впишите сами.",
      sSave: "Сохранить",
      sSaved: "Сохранено.",
      sTraits: "Характер",
      sTraitsNote: "Ползунки влияют на то, как ИИ пишет посты и комментарии.",
      sIdeas: "Идеи постов",
      sIdeasNote: "ИИ пролистает вашу ленту и предложит идеи под текущие тренды: тема + цепляющий хук для каждой.",
      sIdeasGen: "Сгенерировать",
      sIdeasCount: "Количество идей",
      sIdeasHype: "Хайповость",
      sIdeasHypeLo: "Спокойно",
      sIdeasTopic: "Тема (необязательно)",
      sIdeasTopicPh: "например: нейросети, спорт, мемы",
      sIdeasGenerating: "Листаю ленту и придумываю идеи… это займёт ~30 секунд",
      sIdeasEmpty: "Идей пока нет. Нажмите «Сгенерировать».",
      sIdeasUse: "В чат",
      sIdeasDel: "Удалить идею",
      sIdeasFail: "Не удалось сгенерировать идеи",
      sIdeasEmptyResp: "ИИ вернул пустой ответ — попробуйте ещё раз",
      sIdeasBadFormat: "ИИ вернул неожиданный формат —",
      sContinue: "Продолжить",
      sCopy: "Копировать",
      sTrends: "Тренды дня",
      sTrendsRun: "Собрать отчёт",
      sTrendsNote: "ИИ пролистает ленту, проверит темы в поиске и соберёт топ-5 тем дня с примерами и идеей поста для вас. Отчёты хранятся здесь (последние 7).",
      sTrendsRunning: "Собираю тренды… это займёт 1–2 минуты",
      sProgTab: "готовлю вкладку Threads…",
      sProgStep: "шаг {s}/10 · {tool}…",
      sProgReport: "готовлю отчёт…",
      sFiction: "Выдумка",
      sFictionTip: "Выдумка: ИИ придумывает истории-ветки из 2–4 частей",
      sStoryQ: "Вопрос {i} из {n}",
      sStorySkip: "Без уточнений — писать сразу",
      sAnalytics: "Аналитика последних 5 постов",
      sAnRun: "Провести аналитику",
      sAnRefresh: "Обновить",
      sAnWorking: "Собираю данные и анализирую…",
      sAnEmpty: "Посты не найдены — проверьте, что вы вошли в Threads, и обновите страницу",
      sAnNote: "Открывает ваш профиль, берёт последние 5 постов и показывает, что заходит, а что нет.",      sPacing: "Защита от бана",
      sPacingOn: "Паузы между действиями",
      sPacingDelay: "Базовая пауза (сек)",
      sPacingLimit: "Лимит действий в час",
      sPacingNote: "Перед черновиком, публикацией и ответами ИИ ждёт случайную паузу (1–3 базовые) и ведёт счётчик действий. При превышении лимита в час — действия блокируются до следующего часа.",
      sSchedule: "Очередь публикаций",
      sScheduleAll: "Запланировать все идеи",
      sScheduleInterval: "Интервал между постами (мин)",
      sScheduleWorking: "Превращаю идеи в посты и ставлю в очередь…",
      sScheduleDone: "Запланировано постов: {n}",
      sScheduleFail: "Не удалось запланировать",
      sScheduleEmpty: "Очередь пуста. Сначала сгенерируйте идеи.",
      sScheduleDel: "Удалить из очереди",
      sScheduleNow: "Опубликовать сейчас",
      sSchedulePosted: "Опубликован",
      sScheduleErr: "Ошибка",
      sScheduleWait: "Ждёт",
      sScheduleNote: "ИИ превращает каждую идею в готовый пост (≤500 символов, без эмодзи) и ставит его в очередь. Когда наступает время — расширение публикует пост автоматически и уведомляет вас."
    },
    en: {
      brand: "Threads AI",
      newChat: "New chat",
      settings: "Settings",
      placeholder: "Ask the AI…",
      emptyTitle: "Ready to work",
      emptySteps: "Try asking: «What's in my feed?»\n«Find posts about design»\n«Write a post about vacation»\n«Reply to comments on this post»",
      setupTitle: "API key required",
      setupSteps: "Open settings (gear icon)\nand paste your DeepSeek\nor OpenCode Zen key — and you're ready",
      setupBtn: "Settings",
      errNoTab: "Open a Threads tab (threads.com) — the extension only works there.",
      errNotConnected: "Extension is not connected to the page. In Safari: Settings (⌘,) → Extensions → «Threads AI» → «Allow access»: choose «For all websites», then refresh the tab (Cmd+R).",
      cancel: "Cancel",
      publish: "Publish",
      send: "Send",
      publishing: "Publishing…",
      publishLabelPost: "Post ready to publish",
      publishLabelReply: "Reply ready to send",
      connNoKey: "no key",
      connNoTab: "no tab",
      connThreads: "Threads",
      sTitle: "Settings",
      sSub: "DeepSeek-powered assistant for Threads",
      sConn: "Connection",
      sApiKey: "API key",
      show: "Show",
      hide: "Hide",
      sBaseUrl: "Base URL",
      sModel: "Model",
      sCheck: "Test connection",
      sLang: "Interface language",
      sLangLabel: "Language",
      sAuto: "Automation",
      sAutoOn: "Run on schedule",
      sInterval: "Interval (minutes)",
      sTask: "AI task",
      sRunNow: "Run now",
      sAutoNote: "Auto mode reads the feed and writes a report. Publishing and replies only with your confirmation.",
      sStyle: "My style",
      sStyleNote: "The AI will study your posts (it will open your Threads profile) and learn how you write: tone, length, emoji, hashtags. Then it will write posts and replies in your style.",
      sStudy: "Learn my style",
      sClear: "Clear",
      sChecking: "Checking…",
      sCheckOk: "Connected. Model {m}.",
      sCheckOkNoModel: "Connected. Model “{m}” is not in the list, but you can try it.",
      sRunning: "Running…",
      sDone: "Done",
      sRunFail: "Failed to run",
      sNeedTab: "Open a Threads tab (threads.com) — the extension only works there.",
      sStudying: "Studying your profile… takes ~30 seconds",
      sStudyDone: "Done! Style saved.",
      sStudyFail: "Failed to study style",
      sNoPosts: "No posts found on the profile — write a couple of posts and try again.",
      sCleared: "Style cleared.",
      sLastRun: "Last run {time}{err}",
      sErrSuffix: " (with error)",
      sHistory: "Chat history",
      sEmptyHistory: "No saved chats yet",
      sDel: "Delete chat",
      sOpen: "Open chat",
      sNewChatTitle: "Chat",
      sRefreshing: " (refreshing the Threads tab)…",
      sProfile: "My profile",
      sStyleEdit: "Your style — you can edit it manually",
      sStylePh: "Style not studied yet. Press «Learn my style» — or write it yourself.",
      sSave: "Save",
      sSaved: "Saved.",
      sTraits: "Character",
      sTraitsNote: "Sliders affect how the AI writes posts and comments.",
      sIdeas: "Post ideas",
      sIdeasNote: "The AI scrolls your feed and suggests ideas based on current trends: a topic plus a catchy hook for each.",
      sIdeasGen: "Generate",
      sIdeasCount: "Number of ideas",
      sIdeasHype: "Hype level",
      sIdeasHypeLo: "Calm",
      sIdeasTopic: "Topic (optional)",
      sIdeasTopicPh: "e.g. AI, sports, memes",
      sIdeasGenerating: "Scrolling the feed and brainstorming… takes ~30 seconds",
      sIdeasEmpty: "No ideas yet. Press «Generate».",
      sIdeasUse: "To chat",
      sIdeasDel: "Delete idea",
      sIdeasFail: "Failed to generate ideas",
      sIdeasEmptyResp: "The AI returned an empty response — try again",
      sIdeasBadFormat: "The AI returned an unexpected format —",
      sContinue: "Continue",
      sCopy: "Copy",
      sTrends: "Daily trends",
      sTrendsRun: "Collect report",
      sTrendsNote: "The AI scrolls the feed, checks topics in search and collects the top 5 topics of the day with examples and a post idea for you. Reports are stored here (last 7).",
      sTrendsRunning: "Collecting trends… takes 1–2 minutes",
      sProgTab: "preparing the Threads tab…",
      sProgStep: "step {s}/10 · {tool}…",
      sProgReport: "preparing the report…",
      sFiction: "Fiction",
      sFictionTip: "Fiction: the AI makes up thread stories in 2–4 parts",
      sStoryQ: "Question {i} of {n}",
      sStorySkip: "Skip — write now",
      sAnalytics: "Analytics of last 5 posts",
      sAnRun: "Run analytics",
      sAnRefresh: "Refresh",
      sAnWorking: "Collecting data and analyzing…",
      sAnEmpty: "No posts found — make sure you're logged into Threads and refresh the page",
      sAnNote: "Opens your profile, takes the last 5 posts and shows what works and what doesn't.",
      sPacing: "Anti-ban protection",
      sPacingOn: "Pauses between actions",
      sPacingDelay: "Base pause (sec)",
      sPacingLimit: "Actions per hour",
      sPacingNote: "Before drafts, publishing and replies the AI waits a random pause (1–3 base) and keeps an action counter. When the hourly limit is reached, actions are blocked until the next hour.",
      sSchedule: "Publishing queue",
      sScheduleAll: "Schedule all ideas",
      sScheduleInterval: "Interval between posts (min)",
      sScheduleWorking: "Turning ideas into posts and queueing…",
      sScheduleDone: "Scheduled posts: {n}",
      sScheduleFail: "Failed to schedule",
      sScheduleEmpty: "Queue is empty. Generate ideas first.",
      sScheduleDel: "Remove from queue",
      sScheduleNow: "Publish now",
      sSchedulePosted: "Posted",
      sScheduleErr: "Error",
      sScheduleWait: "Waiting",
      sScheduleNote: "The AI turns each idea into a ready post (≤500 chars, no emoji) and queues it. When the time comes, the extension publishes the post automatically and notifies you."
    }
  };

  let LANG = "ru";
  let pending = 0;

  function applyAll() {
    document.documentElement.lang = LANG === "ru" ? "ru" : "en";
    document.querySelectorAll("[data-i18n]").forEach((el) => {
      const key = el.getAttribute("data-i18n");
      const val = I18N[LANG][key];
      if (val !== undefined) el.textContent = val;
    });
    document.querySelectorAll("[data-i18n-ph]").forEach((el) => {
      const key = el.getAttribute("data-i18n-ph");
      const val = I18N[LANG][key];
      if (val !== undefined) el.setAttribute("placeholder", val);
    });
    document.querySelectorAll("[data-i18n-title]").forEach((el) => {
      const key = el.getAttribute("data-i18n-title");
      const val = I18N[LANG][key];
      if (val !== undefined) el.setAttribute("title", val);
    });
  }

  function setLang(lang) {
    if (I18N[lang]) LANG = lang;
    pending++;
    const body = document.body;
    if (body) {
      body.style.transition = "opacity 0.12s ease";
      body.style.opacity = "0";
    }
    setTimeout(() => {
      applyAll();
      if (body) body.style.opacity = "1";
      pending--;
      if (pending < 0) pending = 0;
    }, 120);
  }

  function t(key) {
    return I18N[LANG][key] !== undefined ? I18N[LANG][key] : (I18N.ru[key] !== undefined ? I18N.ru[key] : key);
  }

  window.ThreadsI18n = { setLang, t, dict: I18N };
})();
